/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guitarshopmanagementsystem;
import java.awt.Toolkit;

/**
 *
 * @author quoca
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form HomeJFrm
     */
    public Home() {
    	setTitle("Phần mềm quản lý shop đàn guitar");
    	setIconImage(Toolkit.getDefaultToolkit().getImage(Home.class.getResource("/img/Users.png")));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        trangchumenu = new javax.swing.JMenuItem();
        doimatkhaumenu = new javax.swing.JMenuItem();
        dangxuatmenu = new javax.swing.JMenuItem();
        thoatmenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        acousticmenu = new javax.swing.JMenuItem();
        classicmenu = new javax.swing.JMenuItem();
        electricmenu = new javax.swing.JMenuItem();
        bassmenu = new javax.swing.JMenuItem();
        phukienmenu = new javax.swing.JMenuItem();
        tatcasanphammenu = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        donhangmenu = new javax.swing.JMenuItem();
        khachhangmenui = new javax.swing.JMenuItem();
        thongkemenu = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        phienbanmenu = new javax.swing.JMenuItem();
        banquyenmenu = new javax.swing.JMenuItem();
        lienhemenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("Hệ thống");

        trangchumenu.setText("Trang chủ");
        trangchumenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trangchumenuActionPerformed(evt);
            }
        });
        jMenu1.add(trangchumenu);

        doimatkhaumenu.setText("Đổi mật khẩu");
        doimatkhaumenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doimatkhaumenuActionPerformed(evt);
            }
        });
        jMenu1.add(doimatkhaumenu);

        dangxuatmenu.setText("Đăng xuất");
        dangxuatmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangxuatmenuActionPerformed(evt);
            }
        });
        jMenu1.add(dangxuatmenu);

        thoatmenu.setText("Thoát");
        thoatmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatmenuActionPerformed(evt);
            }
        });
        jMenu1.add(thoatmenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sản phẩm");

        jMenu6.setText("Guitar");

        acousticmenu.setText("Acoustic");
        jMenu6.add(acousticmenu);

        classicmenu.setText("Classic");
        jMenu6.add(classicmenu);

        electricmenu.setText("Electric");
        jMenu6.add(electricmenu);

        bassmenu.setText("Bass");
        jMenu6.add(bassmenu);

        jMenu2.add(jMenu6);

        phukienmenu.setText("Phụ kiện");
        phukienmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phukienmenuActionPerformed(evt);
            }
        });
        jMenu2.add(phukienmenu);

        tatcasanphammenu.setText("Tất cả sản phẩm");
        tatcasanphammenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tatcasanphammenuActionPerformed(evt);
            }
        });
        jMenu2.add(tatcasanphammenu);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Tác vụ");

        donhangmenu.setText("Đơn hàng");
        donhangmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donhangmenuActionPerformed(evt);
            }
        });
        jMenu4.add(donhangmenu);

        khachhangmenui.setText("Khách hàng");
        khachhangmenui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khachhangmenuiActionPerformed(evt);
            }
        });
        jMenu4.add(khachhangmenui);

        thongkemenu.setText("Thống kê");
        jMenu4.add(thongkemenu);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Thông tin");

        phienbanmenu.setText("Phiên bản");
        jMenu5.add(phienbanmenu);

        banquyenmenu.setText("Bản quyền");
        jMenu5.add(banquyenmenu);

        lienhemenu.setText("Liên hệ");
        jMenu5.add(lienhemenu);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void trangchumenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trangchumenuActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_trangchumenuActionPerformed

    private void dangxuatmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangxuatmenuActionPerformed
        // TODO add your handling code here:
        DangNhap dn = new DangNhap();
        dn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dangxuatmenuActionPerformed

    private void thoatmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoatmenuActionPerformed
        // TODO add your handling code here:S
        System.exit(0);
    }//GEN-LAST:event_thoatmenuActionPerformed

    private void doimatkhaumenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doimatkhaumenuActionPerformed
        // TODO add your handling code here:
        DoiMatKhau2 dmk = new DoiMatKhau2();
        dmk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_doimatkhaumenuActionPerformed

    private void tatcasanphammenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tatcasanphammenuActionPerformed
        // TODO add your handling code here:
        // Tạo panel mới
        TatCaSanPhamJP tcsp = new TatCaSanPhamJP();

        // Đặt panel là nội dung của frame Home
        Home home = new Home();
        home.setContentPane(tcsp);

        // Hiển thị frame Home
        home.setVisible(true);

        // Đóng frame hiện tại (nếu có)
        this.dispose();
    }//GEN-LAST:event_tatcasanphammenuActionPerformed

    private void phukienmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phukienmenuActionPerformed
        // TODO add your handling code here:
        // Tạo panel mới
        PhuKienJP pk = new PhuKienJP();

        // Đặt panel là nội dung của frame Home
        Home home = new Home();
        home.setContentPane(pk);

        // Hiển thị frame Home
        home.setVisible(true);

        // Đóng frame hiện tại (nếu có)
        this.dispose();
    }//GEN-LAST:event_phukienmenuActionPerformed

    private void khachhangmenuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khachhangmenuiActionPerformed
        // TODO add your handling code here:
        // Tạo panel mới
        KhachHangJP2 khjp = new KhachHangJP2();

        // Đặt panel là nội dung của frame Home
        Home home = new Home();
        home.setContentPane(khjp);
        
        // Hiển thị frame Home
        home.setVisible(true);

        // Đóng frame hiện tại (nếu có)
        this.dispose();
    }//GEN-LAST:event_khachhangmenuiActionPerformed

    private void donhangmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donhangmenuActionPerformed
        // TODO add your handling code here:
        DonHangJP dh = new DonHangJP();

        // Đặt panel là nội dung của frame Home
        Home home = new Home();
        home.setContentPane(dh);
        
        // Hiển thị frame Home
        home.setVisible(true);

        // Đóng frame hiện tại (nếu có)
        this.dispose();
    }//GEN-LAST:event_donhangmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acousticmenu;
    private javax.swing.JMenuItem banquyenmenu;
    private javax.swing.JMenuItem bassmenu;
    private javax.swing.JMenuItem classicmenu;
    private javax.swing.JMenuItem dangxuatmenu;
    private javax.swing.JMenuItem doimatkhaumenu;
    private javax.swing.JMenuItem donhangmenu;
    private javax.swing.JMenuItem electricmenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem khachhangmenui;
    private javax.swing.JMenuItem lienhemenu;
    private javax.swing.JMenuItem phienbanmenu;
    private javax.swing.JMenuItem phukienmenu;
    private javax.swing.JMenuItem tatcasanphammenu;
    private javax.swing.JMenuItem thoatmenu;
    private javax.swing.JMenuItem thongkemenu;
    private javax.swing.JMenuItem trangchumenu;
    // End of variables declaration//GEN-END:variables
}
