/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guitarshopmanagementsystem;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;

/**
 *
 * @author quoca
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form HomeJFrm
     */
    public Home() {
    	setTitle("Phần mềm quản lý shop đàn guitar");
    	setIconImage(Toolkit.getDefaultToolkit().getImage(Home.class.getResource("/img/Users.png")));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        trangchumenu = new javax.swing.JMenuItem();
        doimatkhaumenu = new javax.swing.JMenuItem();
        dangxuatmenu = new javax.swing.JMenuItem();
        thoatmenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        acousticmenu = new javax.swing.JMenuItem();
        classicmenu = new javax.swing.JMenuItem();
        electricmenu = new javax.swing.JMenuItem();
        bassmenu = new javax.swing.JMenuItem();
        phukienmenu = new javax.swing.JMenuItem();
        tatcasanphammenu = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        donhangmenu = new javax.swing.JMenuItem();
        khachhangmenui = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        phienbanmenu = new javax.swing.JMenuItem();
        banquyenmenu = new javax.swing.JMenuItem();
        lienhemenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        jMenu1.setText("Hệ thống");

        trangchumenu.setText("Trang chủ");
        trangchumenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trangchumenuActionPerformed(evt);
            }
        });
        jMenu1.add(trangchumenu);

        doimatkhaumenu.setText("Đổi mật khẩu");
        doimatkhaumenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doimatkhaumenuActionPerformed(evt);
            }
        });
        jMenu1.add(doimatkhaumenu);

        dangxuatmenu.setText("Đăng xuất");
        dangxuatmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangxuatmenuActionPerformed(evt);
            }
        });
        jMenu1.add(dangxuatmenu);

        thoatmenu.setText("Thoát");
        thoatmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatmenuActionPerformed(evt);
            }
        });
        jMenu1.add(thoatmenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sản phẩm");

        jMenu6.setText("Guitar");

        acousticmenu.setText("Acoustic");
        jMenu6.add(acousticmenu);
        acousticmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	acousticmenuActionPerformed(evt);
            }
        });

        classicmenu.setText("Classic");
        jMenu6.add(classicmenu);
        classicmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	classicmenuActionPerformed(evt);
            }
        });

        electricmenu.setText("Electric");
        jMenu6.add(electricmenu);
        electricmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	electricmenuActionPerformed(evt);
            }
        });


        bassmenu.setText("Bass");
        jMenu6.add(bassmenu);
        bassmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	bassmenuActionPerformed(evt);
            }
        });


        jMenu2.add(jMenu6);

        phukienmenu.setText("Phụ kiện");
        phukienmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phukienmenuActionPerformed(evt);
            }
        });
        jMenu2.add(phukienmenu);

        tatcasanphammenu.setText("Tất cả sản phẩm");
        tatcasanphammenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tatcasanphammenuActionPerformed(evt);
            }
        });
        jMenu2.add(tatcasanphammenu);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Tác vụ");

        donhangmenu.setText("Đơn hàng");
        donhangmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donhangmenuActionPerformed(evt);
            }
        });
        jMenu4.add(donhangmenu);

        khachhangmenui.setText("Khách hàng");
        khachhangmenui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khachhangmenuiActionPerformed(evt);
            }
        });
        jMenu4.add(khachhangmenui);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Thông tin");

        phienbanmenu.setText("Phiên bản");
        jMenu5.add(phienbanmenu);
        phienbanmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	phienbanmenuActionPerformed(evt);
            }
        });


        banquyenmenu.setText("Bản quyền");
        jMenu5.add(banquyenmenu);
        banquyenmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	banquyenmenuActionPerformed(evt);
            }
        });


        lienhemenu.setText("Liên hệ");
        jMenu5.add(lienhemenu);
        lienhemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	lienhemenuActionPerformed(evt);
            }
        });


        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);
        
        lblNewLabel = new JLabel("");
        lblNewLabel.setHorizontalAlignment(SwingConstants.CENTER);
        lblNewLabel.setIcon(new ImageIcon(Home.class.getResource("/img/HomeAlone.jpg")));
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(lblNewLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(lblNewLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void trangchumenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trangchumenuActionPerformed
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_trangchumenuActionPerformed

    private void dangxuatmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangxuatmenuActionPerformed
        DangNhap dn = new DangNhap();
        dn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dangxuatmenuActionPerformed

    private void thoatmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoatmenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_thoatmenuActionPerformed

    private void doimatkhaumenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doimatkhaumenuActionPerformed
        DoiMatKhau dmk = new DoiMatKhau();
        dmk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_doimatkhaumenuActionPerformed

    private void tatcasanphammenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tatcasanphammenuActionPerformed
        TatCaSanPhamJP tcsp = new TatCaSanPhamJP();
        Home home = new Home();
        home.setContentPane(tcsp);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tatcasanphammenuActionPerformed

    private void phukienmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phukienmenuActionPerformed
        PhuKienJP pk = new PhuKienJP();
        Home home = new Home();
        home.setContentPane(pk);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_phukienmenuActionPerformed

    private void khachhangmenuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khachhangmenuiActionPerformed
        KhachHangJP khjp = new KhachHangJP();
        Home home = new Home();
        home.setContentPane(khjp);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_khachhangmenuiActionPerformed

    private void donhangmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donhangmenuActionPerformed
        DonHangJP dh = new DonHangJP();
        Home home = new Home();
        home.setContentPane(dh);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_donhangmenuActionPerformed
    
    private void acousticmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acousticmenuActionPerformed
        AcousticJP ac = new AcousticJP();
        Home home = new Home();
        home.setContentPane(ac);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_acousticmenuActionPerformed

    private void classicmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classicmenuActionPerformed
        ClassicJP cl = new ClassicJP();
        Home home = new Home();
        home.setContentPane(cl);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_classicmenuActionPerformed

    private void electricmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electricmenuActionPerformed
        ElectricJP el = new ElectricJP();
        Home home = new Home();
        home.setContentPane(el);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_electricmenuActionPerformed

    private void bassmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bassmenuActionPerformed
        BassJP ba = new BassJP();
        Home home = new Home();
        home.setContentPane(ba);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bassmenuActionPerformed

    private void phienbanmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phienbanmenuActionPerformed
        JOptionPane.showMessageDialog(this, "Phiên bản 1.3", "Phiên bản", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_phienbanmenuActionPerformed

    private void banquyenmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banquyenmenuActionPerformed
        JOptionPane.showMessageDialog(this, "Bản quyền thuộc sở hữu của Lê Quốc Ân, Nguyễn Quang Sáng, Nguyễn Văn Thắng", "Bản quyền", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_banquyenmenuActionPerformed

    private void lienhemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lienhemenuActionPerformed
        LienHeJP lh = new LienHeJP();
        Home home = new Home();
        home.setContentPane(lh);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lienhemenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acousticmenu;
    private javax.swing.JMenuItem banquyenmenu;
    private javax.swing.JMenuItem bassmenu;
    private javax.swing.JMenuItem classicmenu;
    private javax.swing.JMenuItem dangxuatmenu;
    private javax.swing.JMenuItem doimatkhaumenu;
    private javax.swing.JMenuItem donhangmenu;
    private javax.swing.JMenuItem electricmenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem khachhangmenui;
    private javax.swing.JMenuItem lienhemenu;
    private javax.swing.JMenuItem phienbanmenu;
    private javax.swing.JMenuItem phukienmenu;
    private javax.swing.JMenuItem tatcasanphammenu;
    private javax.swing.JMenuItem thoatmenu;
    private javax.swing.JMenuItem trangchumenu;
    private JLabel lblNewLabel;
    // End of variables declaration//GEN-END:variables
}
