/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package guitarshopmanagementsystem;

import java.awt.Component;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.beans.Customizer;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.RootPaneUI;
import javax.swing.table.*;

import java.sql.Statement;
import java.util.UUID;

/**
 *
 * @author quoca
 */
public class KhachHangJP2 extends javax.swing.JPanel {
    DefaultTableModel tableModel;
    int currentPos = -1;
    public KhachHangJP2() {
        initComponents();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://127.0.0.1:3306/guitarshop";
            Connection con = DriverManager.getConnection(url,"root","01082003");
            String sql = "select * from khachhang"; 
            PreparedStatement ps = con.prepareCall(sql);
            ResultSet rs = ps.executeQuery();
            
            DefaultTableModel model = new DefaultTableModel();
            
            ResultSetMetaData rsmd = rs.getMetaData();
			int socot = rsmd.getColumnCount();
			for(int j = 1; j <= socot; j++) {
				model.addColumn(rsmd.getColumnLabel(j));
			}
			
			while(rs.next()) {
				Object[] row = new Object[socot];
				for(int i = 1; i <= socot; i++) {
					row[i - 1] = rs.getObject(i);
				}
				model.addRow(row);
			}
			tbKhachHang.setModel(model);
			tbKhachHang.setVisible(true);
	
    	} catch(Exception e) {}
        tbKhachHang.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = tbKhachHang.getSelectedRow();
                if (row >= 0) {
                    String hoTen = tbKhachHang.getValueAt(row, 1).toString();
                    String soDienThoai = tbKhachHang.getValueAt(row, 2).toString();
                    String diaChi = tbKhachHang.getValueAt(row, 3).toString();
                    txtHoTen.setText(hoTen);
                    txtSoDienThoai.setText(soDienThoai);
                    txtDiaChi.setText(diaChi);
                }
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbKhachHang = new javax.swing.JTable();

        jLabel1.setText("QUẢN LÝ DANH MỤC KHÁCH HÀNG");

        jLabel2.setText("Họ tên khách hàng:");

        jLabel3.setText("Số điện thoại");

        jLabel4.setText("Địa chỉ:");

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(txtSoDienThoai)
                            .addComponent(txtDiaChi))
                        .addGap(42, 42, 42)
                        .addComponent(btnLuu)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)
                        .addGap(18, 18, 18)
                        .addComponent(btnTimKiem)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuu)
                    .addComponent(btnXoa)
                    .addComponent(btnTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

		        tbKhachHang.setModel(new DefaultTableModel(
            	new Object[][] {
            		{null, null, null, null},
            		{null, null, null, null},
            		{null, null, null, null},
            		{null, null, null, null},
            	},
            	new String[] {
            		"id", "Hoten", "sdt", "diachi"
            	}
            ));
            jScrollPane1.setViewportView(tbKhachHang);
            if (tbKhachHang.getColumnModel().getColumnCount() > 0) {
                tbKhachHang.getColumnModel().getColumn(0).setResizable(false);
                tbKhachHang.getColumnModel().getColumn(1).setResizable(false);
                tbKhachHang.getColumnModel().getColumn(2).setResizable(false);
                tbKhachHang.getColumnModel().getColumn(3).setResizable(false);
            }
		
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
    	try {
            UUID uuid = UUID.randomUUID();
            String randomString = uuid.toString().substring(0, 8);
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://127.0.0.1:3306/guitarshop";
            Connection con = DriverManager.getConnection(url,"root","01082003");
            String sql = "select * from khachhang";
            String sql2 = "insert into khachhang (id, hoten, sdt, diachi) values ('" + randomString + "', '" + txtHoTen.getText() + "', '" + txtSoDienThoai.getText() + "', '" + txtDiaChi.getText() + "');";
            String sql3 = "SELECT * FROM khachhang WHERE hoten = '" + txtHoTen.getText() + "' AND sdt = '" + txtSoDienThoai.getText() + "' AND diachi = '" + txtDiaChi.getText() + "'";
            Statement ps = con.createStatement();
            
            ResultSet rs2 = ps.executeQuery(sql3);
            if(rs2.next()){
                System.out.println("Tồn tại");
                JOptionPane.showMessageDialog(this, "Khách hàng đã tồn tại!");
            } else{
            ps.executeUpdate(sql2);
            ResultSet rs = ps.executeQuery(sql);
            
            DefaultTableModel model = new DefaultTableModel();
            
            ResultSetMetaData rsmd = rs.getMetaData();
			int socot = rsmd.getColumnCount();
			for(int j = 1; j <= socot; j++) {
				model.addColumn(rsmd.getColumnLabel(j));
			}
			
			while(rs.next()) {
				Object[] row = new Object[socot];
				for(int i = 1; i <= socot; i++) {
					row[i - 1] = rs.getObject(i);
				}
				model.addRow(row);
			}
			tbKhachHang.setModel(model);
			tbKhachHang.setVisible(true);
            }            
    	} catch(Exception e) {}
    }//GEN-LAST:event_btnLuuActionPerformed

    private void tbKhachHangMouseClicked(java.awt.event.MouseEvent evt) {                                          
        int row = tbKhachHang.getSelectedRow();
        if (row >= 0) {
            // Lấy thông tin của hàng được chọn.
            String hoTen = tbKhachHang.getValueAt(row, 1).toString();
            String soDienThoai = tbKhachHang.getValueAt(row, 2).toString();
            String diaChi = tbKhachHang.getValueAt(row, 3).toString();

            // Lưu thông tin của hàng được chọn vào các trường tương ứng.
            txtHoTen.setText(hoTen);
            txtSoDienThoai.setText(soDienThoai);
            txtDiaChi.setText(diaChi);
        }
    }
    
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String hoTen = txtHoTen.getText();
        String sdt = txtSoDienThoai.getText();
        String diachi = txtDiaChi.getText();
        if(!hoTen.isEmpty())
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://127.0.0.1:3306/guitarshop";
            Connection con = DriverManager.getConnection(url,"root","01082003");
            String sql = "select * from khachhang";
            String sql2 = "delete from khachhang where hoten = ? and sdt = ? and diachi = ?";
            //String sql2 = "insert into khachhang2 (hoten, sdt, diachi) values ('" + txtHoTen.getText() + "', '" + txtSoDienThoai.getText() + "', '" + txtDiaChi.getText() + "');";
            Statement ps = con.createStatement();
            PreparedStatement ps2 = con.prepareStatement(sql2);
            ps2.setString(1, hoTen);
            ps2.setString(2, sdt);
            ps2.setString(3, diachi);
            
            int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
            if(option == JOptionPane.YES_OPTION) {
	            ps2.executeUpdate();
	            
	            txtHoTen.setText("");
	            txtSoDienThoai.setText("");
	            txtDiaChi.setText("");
	            
	            ResultSet rs = ps.executeQuery(sql);
	            
	            DefaultTableModel model = new DefaultTableModel();
	            
	            ResultSetMetaData rsmd = rs.getMetaData();
				int socot = rsmd.getColumnCount();
				for(int j = 1; j <= socot; j++) {
					model.addColumn(rsmd.getColumnLabel(j));
				}
				
				while(rs.next()) {
					Object[] row = new Object[socot];
					for(int i = 1; i <= socot; i++) {
						row[i - 1] = rs.getObject(i);
					}
					model.addRow(row);
				}
				tbKhachHang.setModel(model);
				tbKhachHang.setVisible(true);
            }
            else {
            	return;
            }
    	} catch(Exception e) {}
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
    	String s = JOptionPane.showInputDialog("Nhập vào tên khách hàng muốn tìm kiếm");
        if(!s.isEmpty()){
            s = "%"+s+"%";
            System.out.println(s);
	        try {
	            Class.forName("com.mysql.jdbc.Driver");
	            String url = "jdbc:mysql://127.0.0.1:3306/guitarshop";
	            Connection con = DriverManager.getConnection(url,"root","01082003");
	            String sql = "select * from khachhang where hoten like ?;";
				PreparedStatement ps2 = con.prepareStatement(sql);
	            ps2.setString(1, s);
	            
	            ResultSet rs = ps2.executeQuery();
	            
	            if (!rs.next()) {
	                // Thông báo lỗi không có khách hàng nào được tìm thấy ở đây
	                JOptionPane.showMessageDialog(null, "Không tìm thấy khách hàng!");
	            } else {
	                DefaultTableModel model = new DefaultTableModel();
	                
	                ResultSetMetaData rsmd = rs.getMetaData();
	                int socot = rsmd.getColumnCount();
	                for(int j = 1; j <= socot; j++) {
	                    model.addColumn(rsmd.getColumnLabel(j));
	                }
	                do {
	                    Object[] row = new Object[socot];
	                    for(int i = 1; i <= socot; i++) {
	                        row[i - 1] = rs.getObject(i);
	                    }
	                    model.addRow(row);
	                } while (rs.next());
	                tbKhachHang.setModel(model);
	                tbKhachHang.setVisible(true);
	            }
	    	} catch(Exception e) {}
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbKhachHang;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtSoDienThoai;
    // End of variables declaration//GEN-END:variables
}
